/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as TeachersNewRouteImport } from './routes/teachers/new'
import { Route as StudentsNewRouteImport } from './routes/students/new'
import { Route as StaffNewRouteImport } from './routes/staff/new'
import { Route as ParentsNewRouteImport } from './routes/parents/new'
import { Route as TeachersTeacherIdEditRouteImport } from './routes/teachers/$teacherId/edit'
import { Route as StudentsStudentIdEditRouteImport } from './routes/students/$studentId/edit'
import { Route as StaffStaffIdEditRouteImport } from './routes/staff/$staffId/edit'
import { Route as ParentsParentIdEditRouteImport } from './routes/parents/$parentId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersNewRoute = TeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsNewRoute = ParentsNewRouteImport.update({
  id: '/parents/new',
  path: '/parents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdEditRoute = TeachersTeacherIdEditRouteImport.update({
  id: '/teachers/$teacherId/edit',
  path: '/teachers/$teacherId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdEditRoute = StudentsStudentIdEditRouteImport.update({
  id: '/students/$studentId/edit',
  path: '/students/$studentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdEditRoute = StaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentIdEditRoute = ParentsParentIdEditRouteImport.update({
  id: '/parents/$parentId/edit',
  path: '/parents/$parentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parents/new': typeof ParentsNewRoute
  '/staff/new': typeof StaffNewRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/parents/': typeof ParentsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/parents/$parentId/edit': typeof ParentsParentIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parents/new': typeof ParentsNewRoute
  '/staff/new': typeof StaffNewRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/parents': typeof ParentsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/parents/$parentId/edit': typeof ParentsParentIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parents/new': typeof ParentsNewRoute
  '/staff/new': typeof StaffNewRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/parents/': typeof ParentsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/parents/$parentId/edit': typeof ParentsParentIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parents/new'
    | '/staff/new'
    | '/students/new'
    | '/teachers/new'
    | '/parents/'
    | '/staff/'
    | '/students/'
    | '/teachers/'
    | '/parents/$parentId/edit'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/teachers/$teacherId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parents/new'
    | '/staff/new'
    | '/students/new'
    | '/teachers/new'
    | '/parents'
    | '/staff'
    | '/students'
    | '/teachers'
    | '/parents/$parentId/edit'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/teachers/$teacherId/edit'
  id:
    | '__root__'
    | '/'
    | '/parents/new'
    | '/staff/new'
    | '/students/new'
    | '/teachers/new'
    | '/parents/'
    | '/staff/'
    | '/students/'
    | '/teachers/'
    | '/parents/$parentId/edit'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/teachers/$teacherId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParentsNewRoute: typeof ParentsNewRoute
  StaffNewRoute: typeof StaffNewRoute
  StudentsNewRoute: typeof StudentsNewRoute
  TeachersNewRoute: typeof TeachersNewRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  ParentsParentIdEditRoute: typeof ParentsParentIdEditRoute
  StaffStaffIdEditRoute: typeof StaffStaffIdEditRoute
  StudentsStudentIdEditRoute: typeof StudentsStudentIdEditRoute
  TeachersTeacherIdEditRoute: typeof TeachersTeacherIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/new': {
      id: '/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof TeachersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/new': {
      id: '/parents/new'
      path: '/parents/new'
      fullPath: '/parents/new'
      preLoaderRoute: typeof ParentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId/edit': {
      id: '/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/teachers/$teacherId/edit'
      preLoaderRoute: typeof TeachersTeacherIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/edit': {
      id: '/students/$studentId/edit'
      path: '/students/$studentId/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof StudentsStudentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId/edit': {
      id: '/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof StaffStaffIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/$parentId/edit': {
      id: '/parents/$parentId/edit'
      path: '/parents/$parentId/edit'
      fullPath: '/parents/$parentId/edit'
      preLoaderRoute: typeof ParentsParentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParentsNewRoute: ParentsNewRoute,
  StaffNewRoute: StaffNewRoute,
  StudentsNewRoute: StudentsNewRoute,
  TeachersNewRoute: TeachersNewRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  ParentsParentIdEditRoute: ParentsParentIdEditRoute,
  StaffStaffIdEditRoute: StaffStaffIdEditRoute,
  StudentsStudentIdEditRoute: StudentsStudentIdEditRoute,
  TeachersTeacherIdEditRoute: TeachersTeacherIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
