/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as TeachersNewRouteImport } from './routes/teachers/new'
import { Route as StudentsNewRouteImport } from './routes/students/new'
import { Route as StaffNewRouteImport } from './routes/staff/new'
import { Route as ParentsNewRouteImport } from './routes/parents/new'
import { Route as ClassesNewRouteImport } from './routes/classes/new'
import { Route as ClassesClassIdIndexRouteImport } from './routes/classes/$classId/index'
import { Route as TeachersTeacherIdEditRouteImport } from './routes/teachers/$teacherId/edit'
import { Route as StudentsStudentIdEditRouteImport } from './routes/students/$studentId/edit'
import { Route as StaffStaffIdEditRouteImport } from './routes/staff/$staffId/edit'
import { Route as ParentsParentIdEditRouteImport } from './routes/parents/$parentId/edit'
import { Route as ClassesClassIdGradesRouteImport } from './routes/classes/$classId/grades'
import { Route as ClassesClassIdEditRouteImport } from './routes/classes/$classId/edit'
import { Route as ClassesClassIdLessonsNewRouteImport } from './routes/classes/$classId/lessons/new'
import { Route as ClassesClassIdLessonsLessonIdGradesRouteImport } from './routes/classes/$classId/lessons/$lessonId/grades'
import { Route as ClassesClassIdLessonsLessonIdEditRouteImport } from './routes/classes/$classId/lessons/$lessonId/edit'
import { Route as ClassesClassIdLessonsLessonIdAttendanceRouteImport } from './routes/classes/$classId/lessons/$lessonId/attendance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersNewRoute = TeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsNewRoute = ParentsNewRouteImport.update({
  id: '/parents/new',
  path: '/parents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesNewRoute = ClassesNewRouteImport.update({
  id: '/classes/new',
  path: '/classes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdIndexRoute = ClassesClassIdIndexRouteImport.update({
  id: '/classes/$classId/',
  path: '/classes/$classId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdEditRoute = TeachersTeacherIdEditRouteImport.update({
  id: '/teachers/$teacherId/edit',
  path: '/teachers/$teacherId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdEditRoute = StudentsStudentIdEditRouteImport.update({
  id: '/students/$studentId/edit',
  path: '/students/$studentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdEditRoute = StaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentIdEditRoute = ParentsParentIdEditRouteImport.update({
  id: '/parents/$parentId/edit',
  path: '/parents/$parentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdGradesRoute = ClassesClassIdGradesRouteImport.update({
  id: '/classes/$classId/grades',
  path: '/classes/$classId/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdEditRoute = ClassesClassIdEditRouteImport.update({
  id: '/classes/$classId/edit',
  path: '/classes/$classId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdLessonsNewRoute =
  ClassesClassIdLessonsNewRouteImport.update({
    id: '/classes/$classId/lessons/new',
    path: '/classes/$classId/lessons/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassesClassIdLessonsLessonIdGradesRoute =
  ClassesClassIdLessonsLessonIdGradesRouteImport.update({
    id: '/classes/$classId/lessons/$lessonId/grades',
    path: '/classes/$classId/lessons/$lessonId/grades',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassesClassIdLessonsLessonIdEditRoute =
  ClassesClassIdLessonsLessonIdEditRouteImport.update({
    id: '/classes/$classId/lessons/$lessonId/edit',
    path: '/classes/$classId/lessons/$lessonId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassesClassIdLessonsLessonIdAttendanceRoute =
  ClassesClassIdLessonsLessonIdAttendanceRouteImport.update({
    id: '/classes/$classId/lessons/$lessonId/attendance',
    path: '/classes/$classId/lessons/$lessonId/attendance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes/new': typeof ClassesNewRoute
  '/parents/new': typeof ParentsNewRoute
  '/staff/new': typeof StaffNewRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/classes/': typeof ClassesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/classes/$classId/edit': typeof ClassesClassIdEditRoute
  '/classes/$classId/grades': typeof ClassesClassIdGradesRoute
  '/parents/$parentId/edit': typeof ParentsParentIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
  '/classes/$classId/': typeof ClassesClassIdIndexRoute
  '/classes/$classId/lessons/new': typeof ClassesClassIdLessonsNewRoute
  '/classes/$classId/lessons/$lessonId/attendance': typeof ClassesClassIdLessonsLessonIdAttendanceRoute
  '/classes/$classId/lessons/$lessonId/edit': typeof ClassesClassIdLessonsLessonIdEditRoute
  '/classes/$classId/lessons/$lessonId/grades': typeof ClassesClassIdLessonsLessonIdGradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes/new': typeof ClassesNewRoute
  '/parents/new': typeof ParentsNewRoute
  '/staff/new': typeof StaffNewRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/classes': typeof ClassesIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/parents': typeof ParentsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/classes/$classId/edit': typeof ClassesClassIdEditRoute
  '/classes/$classId/grades': typeof ClassesClassIdGradesRoute
  '/parents/$parentId/edit': typeof ParentsParentIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
  '/classes/$classId': typeof ClassesClassIdIndexRoute
  '/classes/$classId/lessons/new': typeof ClassesClassIdLessonsNewRoute
  '/classes/$classId/lessons/$lessonId/attendance': typeof ClassesClassIdLessonsLessonIdAttendanceRoute
  '/classes/$classId/lessons/$lessonId/edit': typeof ClassesClassIdLessonsLessonIdEditRoute
  '/classes/$classId/lessons/$lessonId/grades': typeof ClassesClassIdLessonsLessonIdGradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes/new': typeof ClassesNewRoute
  '/parents/new': typeof ParentsNewRoute
  '/staff/new': typeof StaffNewRoute
  '/students/new': typeof StudentsNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/classes/': typeof ClassesIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/classes/$classId/edit': typeof ClassesClassIdEditRoute
  '/classes/$classId/grades': typeof ClassesClassIdGradesRoute
  '/parents/$parentId/edit': typeof ParentsParentIdEditRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/students/$studentId/edit': typeof StudentsStudentIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
  '/classes/$classId/': typeof ClassesClassIdIndexRoute
  '/classes/$classId/lessons/new': typeof ClassesClassIdLessonsNewRoute
  '/classes/$classId/lessons/$lessonId/attendance': typeof ClassesClassIdLessonsLessonIdAttendanceRoute
  '/classes/$classId/lessons/$lessonId/edit': typeof ClassesClassIdLessonsLessonIdEditRoute
  '/classes/$classId/lessons/$lessonId/grades': typeof ClassesClassIdLessonsLessonIdGradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes/new'
    | '/parents/new'
    | '/staff/new'
    | '/students/new'
    | '/teachers/new'
    | '/classes/'
    | '/lessons/'
    | '/parents/'
    | '/staff/'
    | '/students/'
    | '/teachers/'
    | '/classes/$classId/edit'
    | '/classes/$classId/grades'
    | '/parents/$parentId/edit'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/teachers/$teacherId/edit'
    | '/classes/$classId/'
    | '/classes/$classId/lessons/new'
    | '/classes/$classId/lessons/$lessonId/attendance'
    | '/classes/$classId/lessons/$lessonId/edit'
    | '/classes/$classId/lessons/$lessonId/grades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes/new'
    | '/parents/new'
    | '/staff/new'
    | '/students/new'
    | '/teachers/new'
    | '/classes'
    | '/lessons'
    | '/parents'
    | '/staff'
    | '/students'
    | '/teachers'
    | '/classes/$classId/edit'
    | '/classes/$classId/grades'
    | '/parents/$parentId/edit'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/teachers/$teacherId/edit'
    | '/classes/$classId'
    | '/classes/$classId/lessons/new'
    | '/classes/$classId/lessons/$lessonId/attendance'
    | '/classes/$classId/lessons/$lessonId/edit'
    | '/classes/$classId/lessons/$lessonId/grades'
  id:
    | '__root__'
    | '/'
    | '/classes/new'
    | '/parents/new'
    | '/staff/new'
    | '/students/new'
    | '/teachers/new'
    | '/classes/'
    | '/lessons/'
    | '/parents/'
    | '/staff/'
    | '/students/'
    | '/teachers/'
    | '/classes/$classId/edit'
    | '/classes/$classId/grades'
    | '/parents/$parentId/edit'
    | '/staff/$staffId/edit'
    | '/students/$studentId/edit'
    | '/teachers/$teacherId/edit'
    | '/classes/$classId/'
    | '/classes/$classId/lessons/new'
    | '/classes/$classId/lessons/$lessonId/attendance'
    | '/classes/$classId/lessons/$lessonId/edit'
    | '/classes/$classId/lessons/$lessonId/grades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesNewRoute: typeof ClassesNewRoute
  ParentsNewRoute: typeof ParentsNewRoute
  StaffNewRoute: typeof StaffNewRoute
  StudentsNewRoute: typeof StudentsNewRoute
  TeachersNewRoute: typeof TeachersNewRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  ClassesClassIdEditRoute: typeof ClassesClassIdEditRoute
  ClassesClassIdGradesRoute: typeof ClassesClassIdGradesRoute
  ParentsParentIdEditRoute: typeof ParentsParentIdEditRoute
  StaffStaffIdEditRoute: typeof StaffStaffIdEditRoute
  StudentsStudentIdEditRoute: typeof StudentsStudentIdEditRoute
  TeachersTeacherIdEditRoute: typeof TeachersTeacherIdEditRoute
  ClassesClassIdIndexRoute: typeof ClassesClassIdIndexRoute
  ClassesClassIdLessonsNewRoute: typeof ClassesClassIdLessonsNewRoute
  ClassesClassIdLessonsLessonIdAttendanceRoute: typeof ClassesClassIdLessonsLessonIdAttendanceRoute
  ClassesClassIdLessonsLessonIdEditRoute: typeof ClassesClassIdLessonsLessonIdEditRoute
  ClassesClassIdLessonsLessonIdGradesRoute: typeof ClassesClassIdLessonsLessonIdGradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/new': {
      id: '/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof TeachersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/new': {
      id: '/parents/new'
      path: '/parents/new'
      fullPath: '/parents/new'
      preLoaderRoute: typeof ParentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/new': {
      id: '/classes/new'
      path: '/classes/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof ClassesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/': {
      id: '/classes/$classId/'
      path: '/classes/$classId'
      fullPath: '/classes/$classId/'
      preLoaderRoute: typeof ClassesClassIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId/edit': {
      id: '/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/teachers/$teacherId/edit'
      preLoaderRoute: typeof TeachersTeacherIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/edit': {
      id: '/students/$studentId/edit'
      path: '/students/$studentId/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof StudentsStudentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId/edit': {
      id: '/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof StaffStaffIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/$parentId/edit': {
      id: '/parents/$parentId/edit'
      path: '/parents/$parentId/edit'
      fullPath: '/parents/$parentId/edit'
      preLoaderRoute: typeof ParentsParentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/grades': {
      id: '/classes/$classId/grades'
      path: '/classes/$classId/grades'
      fullPath: '/classes/$classId/grades'
      preLoaderRoute: typeof ClassesClassIdGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/edit': {
      id: '/classes/$classId/edit'
      path: '/classes/$classId/edit'
      fullPath: '/classes/$classId/edit'
      preLoaderRoute: typeof ClassesClassIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/lessons/new': {
      id: '/classes/$classId/lessons/new'
      path: '/classes/$classId/lessons/new'
      fullPath: '/classes/$classId/lessons/new'
      preLoaderRoute: typeof ClassesClassIdLessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/lessons/$lessonId/grades': {
      id: '/classes/$classId/lessons/$lessonId/grades'
      path: '/classes/$classId/lessons/$lessonId/grades'
      fullPath: '/classes/$classId/lessons/$lessonId/grades'
      preLoaderRoute: typeof ClassesClassIdLessonsLessonIdGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/lessons/$lessonId/edit': {
      id: '/classes/$classId/lessons/$lessonId/edit'
      path: '/classes/$classId/lessons/$lessonId/edit'
      fullPath: '/classes/$classId/lessons/$lessonId/edit'
      preLoaderRoute: typeof ClassesClassIdLessonsLessonIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/lessons/$lessonId/attendance': {
      id: '/classes/$classId/lessons/$lessonId/attendance'
      path: '/classes/$classId/lessons/$lessonId/attendance'
      fullPath: '/classes/$classId/lessons/$lessonId/attendance'
      preLoaderRoute: typeof ClassesClassIdLessonsLessonIdAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesNewRoute: ClassesNewRoute,
  ParentsNewRoute: ParentsNewRoute,
  StaffNewRoute: StaffNewRoute,
  StudentsNewRoute: StudentsNewRoute,
  TeachersNewRoute: TeachersNewRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  ClassesClassIdEditRoute: ClassesClassIdEditRoute,
  ClassesClassIdGradesRoute: ClassesClassIdGradesRoute,
  ParentsParentIdEditRoute: ParentsParentIdEditRoute,
  StaffStaffIdEditRoute: StaffStaffIdEditRoute,
  StudentsStudentIdEditRoute: StudentsStudentIdEditRoute,
  TeachersTeacherIdEditRoute: TeachersTeacherIdEditRoute,
  ClassesClassIdIndexRoute: ClassesClassIdIndexRoute,
  ClassesClassIdLessonsNewRoute: ClassesClassIdLessonsNewRoute,
  ClassesClassIdLessonsLessonIdAttendanceRoute:
    ClassesClassIdLessonsLessonIdAttendanceRoute,
  ClassesClassIdLessonsLessonIdEditRoute:
    ClassesClassIdLessonsLessonIdEditRoute,
  ClassesClassIdLessonsLessonIdGradesRoute:
    ClassesClassIdLessonsLessonIdGradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
